# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix



# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %


# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# When in prefix mode, press 'a' to go to the previous window
bind-key -T prefix a last-window

# Prefix " prompts you which window to select.  You can press TAB to bring up a list
#bind-key -T prefix \" command-prompt -T window-target -pindex { select-window -t ':%%' }

# Prefix " shows a list of windows you can switch to
bind-key -T prefix \" choose-tree -Zw

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind-key -T copy-mode ? command-prompt -i -I "#{pane_search_string}" -T search -p "(search up)" { send-keys -X search-backward-incremental "%%" }
